server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/incident_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always

ai:
  llm:
    base-url: http://100.64.0.1:11434
    model: qwen3-coder:latest
